
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[164] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       58,   57,   12,   12,   13,   13,   30,   31,   28,   26,
       32,   27,   57,   29,   17,   25,   21,   21,   21,   21,
       12,   24,   28,   23,    9,   10,   57,    4,    9,    9,
        8,   37,   56,   57,   57,   43,   44,   53,   51,   36,
       52,   57,   54,   40,   55,   42,   41,   41,   41,   41,
       53,   33,   34,    0,   15,    0,   16,   14,   18,   11,
        0,    0,   17,   21,   21,   25,    0,   21,    0,   33,
       24,   24,    0,   22,   14,   23,    9,    0,    9,    4,
        9,    9,    2,    9,    8,   37,    0,   46,    0,   47,

       45,   48,   39,    0,    0,   40,   41,   41,   42,    0,
       41,    0,    0,   38,   45,   18,   11,   21,   17,   21,
       21,   19,    0,    1,   20,    0,    9,    9,    6,    3,
        9,   48,   39,   41,   40,   41,   41,   49,    0,   35,
       50,    0,   21,   21,   21,    5,    9,    9,    7,    9,
       41,   41,   41,   21,    9,   41,   21,    6,    9,   41,
        1,   35,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   17,   18,    1,   19,
       19,   19,    1,    1,   20,   21,   22,   21,   23,   21,
       24,   25,   26,   24,   24,   24,   24,   24,   24,   27,
       24,   28,   29,   30,   31,   32,   24,   33,   24,   24,
       34,    1,    1,    1,   35,    1,   36,   21,   37,   21,

       38,   21,   24,   25,   39,   24,   24,   24,   24,   24,
       24,   40,   24,   41,   42,   43,   44,   45,   24,   33,
       24,   24,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[46] =
    {   0,
        1,    2,    3,    2,    4,    5,    4,    1,    1,    1,
        1,    1,    5,    6,    1,    7,    7,    1,    1,    7,
        7,    7,    7,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    8,    5,    7,    7,    7,    5,    5,
        5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[190] =
    {   0,
        0,   42,   56,   94,    0,    0,    0,    0,  133,  385,
      394,  640,   47,   51,  380,  374,  640,  640,  355,  640,
      640,  640,   59,  640,  173,  338,   65,  204,   62,   59,
       81,    0,   62,    0,  342,  640,  100,  174,   66,   76,
       60,   73,  640,  339,  333,  640,  640,  327,  640,  640,
      640,  113,  640,  234,  640,  297,  179,  265,  176,  105,
      103,  119,  122,  300,  640,  266,  640,  640,  112,  192,
      191,  196,  295,  210,  196,  640,  215,  325,  220,  226,
        0,    0,  251,  640,  239,    0,  191,    0,  217,  229,
      235,  198,  170,  239,  227,  255,  175,  640,  112,  640,

      640,  115,  260,  252,  273,  357,  279,  275,  640,  276,
      387,  279,  106,  640,   88,  250,  286,  285,  280,  273,
      281,  640,  299,  285,  640,  316,   72,  318,  328,   67,
      332,  308,  348,  320,  350,  321,  331,  640,  370,  339,
      640,  373,  373,  377,  366,  370,  409,  382,   42,  418,
      407,  423,  406,  411,  437,  427,  422,   33,  453,  443,
      367,  394,  640,  481,  489,  497,  505,  513,  517,  525,
      533,  541,  549,  557,  565,  573,  577,  585,  589,  592,
      597,  601,  608,  612,  615,  620,  624,  627,  631
    } ;

static yyconst flex_int16_t yy_def[190] =
    {   0,
      163,    1,  164,  164,  165,  165,  165,  165,  163,    9,
      163,  163,  163,  163,  166,  167,  163,  163,  163,  163,
      163,  163,  168,  163,  169,  163,  169,  169,   28,   28,
      163,  170,  171,  172,  173,  163,  163,  173,  173,  173,
      173,  163,  163,  174,  175,  163,  163,  163,  163,  163,
      163,  176,  163,  177,  163,  163,  177,  177,   58,   58,
      178,  163,  163,  166,  163,  167,  163,  163,  163,  163,
      179,  168,  180,  180,   28,  163,  181,  180,  182,  163,
      170,  170,  171,  163,  171,  172,  173,  183,  173,  173,
      173,  173,  173,  173,  173,  163,  174,  163,  175,  163,

      163,  163,  163,  184,  176,  185,  185,   58,  163,  186,
      185,  187,  178,  163,  178,  163,  163,  188,   78,   78,
       78,  163,  181,   78,  163,  182,  183,  173,  173,  173,
      173,  163,  163,  189,  111,  111,  111,  163,  186,  111,
      163,  187,  188,  188,   78,  173,  173,  173,  173,  173,
      189,  189,  111,   78,  173,  111,   78,  173,  173,  111,
       78,  111,    0,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163
    } ;

static yyconst flex_int16_t yy_nxt[686] =
    {   0,
       12,   13,   14,   13,   15,   12,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   25,   12,   26,   27,
       27,   27,   27,   27,   28,   27,   29,   27,   27,   27,
       27,   27,   30,   12,   12,   27,   27,   27,   27,   29,
       27,   27,   27,   27,   27,   31,   88,   32,   62,   63,
       62,   33,   63,   63,   63,   88,   34,   36,   36,   36,
       70,   70,   70,   79,   84,   79,  163,   94,  163,   37,
       71,   85,   38,   88,   96,   39,   96,   71,  163,   88,
       88,   40,   62,   63,   80,   88,   81,   78,   41,   88,
      114,   39,   95,   92,   40,   36,   36,   36,   75,   71,

       78,   70,   70,   70,   93,  114,   92,   37,  114,  112,
       38,  112,  115,   39,  103,  103,  103,   93,  100,   40,
       62,   63,   62,   63,   63,   63,   41,  116,  116,   39,
      132,  132,   40,   12,   42,   43,   42,   44,   12,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   54,
       55,   56,   57,   57,   57,   57,   57,   58,   57,   59,
       57,   57,   57,   57,   57,   60,   12,   12,   57,   57,
       57,   57,   59,   57,   57,   57,   57,   57,   71,   98,
      163,   89,  163,   88,  104,   71,   72,   88,   73,   73,
       90,  104,  163,  117,  117,  117,   71,  163,  163,  163,

      163,  111,  163,   71,   88,   91,   75,   71,   77,   71,
       77,   88,  108,  104,  111,   71,   71,  163,   91,  122,
      130,  122,   71,  163,  125,   71,  125,   62,   63,   80,
       88,   81,  128,  128,   94,  130,   89,   75,   71,  104,
       88,   84,   88,  121,   71,   90,  104,  105,   88,  106,
      106,  129,   88,   84,  131,  131,   96,  104,   96,   95,
       91,  133,  133,  133,  104,  116,  116,  108,  104,  110,
      104,  110,   67,   91,  163,  163,  163,  104,  163,  163,
      138,  163,  138,  141,  104,  141,  104,  117,  117,  117,
       71,  104,  163,   72,  120,  119,  119,   71,  108,  104,

       71,  120,  120,  122,   65,  122,  120,   71,   72,  120,
      119,  119,  137,  104,  145,  109,  120,  120,  144,   71,
      125,  120,  125,  132,  132,  104,  146,  145,  121,   71,
       71,   88,  104,  147,  147,  148,  101,   71,  163,  100,
      149,   88,  136,   98,  129,   88,  124,  150,  150,  133,
      133,  133,  136,  152,  104,   88,   76,  136,  121,   71,
      136,  124,  104,  105,   68,  135,  135,  136,  153,  104,
      105,  136,  135,  135,  138,  136,  138,  141,   71,  141,
       67,  153,   71,   88,   65,   71,  136,  120,  120,   71,
      137,  104,  104,  163,   61,   88,  154,  155,  155,  104,

      163,   91,  120,  120,  163,  163,  144,   71,  140,  154,
      144,   71,  104,  163,   91,  136,  163,  146,  163,  104,
      137,  104,   88,  140,  147,  147,  149,  136,  104,  163,
      136,   88,  120,  150,  150,  104,  156,  163,  157,  163,
      152,  104,  136,  120,  161,  158,  163,  120,  136,  156,
       88,  157,  159,  159,  160,  163,  152,  104,  120,  161,
      163,  158,  163,  136,  136,  162,   88,  160,  159,  159,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  136,
      162,   35,   35,   35,   35,   35,   35,   35,   35,   12,
       12,   12,   12,   12,   12,   12,   12,   64,   64,  163,

       64,   64,   64,   64,   64,   66,   66,  163,   66,   66,
       66,   66,   66,   69,   69,   69,   69,   69,  163,   69,
       69,   74,   74,   74,   74,   82,   82,  163,   82,   82,
       82,   82,   82,   83,   83,   83,   83,   83,   83,   83,
       83,   86,   86,  163,   86,   86,   86,   86,   86,   87,
      163,  163,   87,   87,   87,   87,   87,   97,   97,  163,
       97,   97,   97,   97,   97,   99,   99,  163,   99,   99,
       99,   99,   99,  102,  102,  102,  102,  102,  163,  102,
      102,  107,  107,  107,  107,  113,  113,  113,  113,  113,
      113,  113,  113,  118,  163,  118,  120,  120,  120,  120,

      123,  163,  163,  123,  126,  163,  163,  126,  127,  163,
      163,  127,  127,  163,  127,  127,  134,  163,  134,  136,
      136,  136,  136,  139,  163,  163,  139,  142,  163,  163,
      142,  143,  163,  143,  143,  151,  163,  151,  151,   11,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163
    } ;

static yyconst flex_int16_t yy_chk[686] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,  158,    2,   13,   13,
       13,    2,   14,   14,   14,  149,    2,    3,    3,    3,
       23,   23,   23,   30,   33,   30,   29,   41,   29,    3,
       27,   33,    3,   41,   42,    3,   42,   27,   27,   39,
      130,    3,   31,   31,   31,  127,   31,   29,    3,   40,
      115,    3,   41,   39,    3,    4,    4,    4,   27,   27,

       29,   37,   37,   37,   40,   61,   39,    4,  113,   60,
        4,   60,   61,    4,   52,   52,   52,   40,   99,    4,
       62,   62,   62,   63,   63,   63,    4,   69,   69,    4,
      102,  102,    4,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,   25,   97,
       59,   38,   59,   93,   57,   25,   25,   38,   25,   25,
       38,   57,   57,   70,   70,   70,   71,   72,   72,   72,

       75,   59,   75,   71,   87,   38,   25,   25,   28,   28,
       28,   92,   57,   57,   59,   74,   28,   28,   38,   77,
       92,   77,   74,   74,   79,   71,   79,   80,   80,   80,
       89,   80,   89,   89,   95,   92,   90,   28,   28,   54,
       95,   85,   90,   74,   74,   90,   54,   54,   91,   54,
       54,   91,   94,   83,   94,   94,   96,  104,   96,   95,
       90,  103,  103,  103,  104,  116,  116,   54,   54,   58,
       58,   58,   66,   90,  105,  105,  105,   58,   58,  108,
      110,  108,  110,  112,  107,  112,  104,  117,  117,  117,
      118,  107,  107,  119,  120,  119,  119,  118,   58,   58,

       73,  119,  121,  123,   64,  123,  124,   73,   73,  120,
       73,   73,  107,  107,  124,   56,  119,  121,  118,  118,
      126,  124,  126,  132,  132,  134,  128,  124,   73,   73,
       78,  128,  134,  128,  128,  129,   48,   78,   78,   45,
      131,  129,  136,   44,  129,  131,   78,  131,  131,  133,
      133,  133,  137,  134,  134,   35,   26,  136,   78,   78,
      140,   78,  106,  135,   19,  135,  135,  137,  140,  106,
      106,  135,  106,  106,  139,  140,  139,  142,  143,  142,
       16,  140,  144,  146,   15,  143,  135,  145,  161,  144,
      106,  106,  111,   11,   10,  148,  145,  148,  148,  111,

      111,  146,  145,  161,    0,    0,  143,  143,  111,  145,
      144,  144,  151,    0,  146,  162,    0,  147,    0,  151,
      111,  111,  147,  111,  147,  147,  150,  153,  152,    0,
      162,  150,  154,  150,  150,  152,  153,    0,  154,    0,
      151,  151,  153,  157,  157,  155,    0,  154,  156,  153,
      155,  154,  155,  155,  156,    0,  152,  152,  157,  157,
        0,  159,    0,  156,  160,  160,  159,  156,  159,  159,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  160,
      160,  164,  164,  164,  164,  164,  164,  164,  164,  165,
      165,  165,  165,  165,  165,  165,  165,  166,  166,    0,

      166,  166,  166,  166,  166,  167,  167,    0,  167,  167,
      167,  167,  167,  168,  168,  168,  168,  168,    0,  168,
      168,  169,  169,  169,  169,  170,  170,    0,  170,  170,
      170,  170,  170,  171,  171,  171,  171,  171,  171,  171,
      171,  172,  172,    0,  172,  172,  172,  172,  172,  173,
        0,    0,  173,  173,  173,  173,  173,  174,  174,    0,
      174,  174,  174,  174,  174,  175,  175,    0,  175,  175,
      175,  175,  175,  176,  176,  176,  176,  176,    0,  176,
      176,  177,  177,  177,  177,  178,  178,  178,  178,  178,
      178,  178,  178,  179,    0,  179,  180,  180,  180,  180,

      181,    0,    0,  181,  182,    0,    0,  182,  183,    0,
        0,  183,  183,    0,  183,  183,  184,    0,  184,  185,
      185,  185,  185,  186,    0,    0,  186,  187,    0,    0,
      187,  188,    0,  188,  188,  189,    0,  189,  189,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "token.l"
/*
 * File: token.l
 * Created Date: Friday April 25th 2014
 * Author: Deepak Purandare
 * -----
 * Last Modified: Friday April 25th 2014 6:09:08 pm
 * Modified By: Deepak Purandare - <deepak_purandare@hotmail.com>
 * -----
 * Copyright (c) 2019 Purndare Consulting
 * This software is made available under GNU General Public License Version 3
 * Visit http://www.gnu.org/licenses/gpl-3.0.html for terms of usage.
 */
#line 19 "token.l"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include "y.tab.h"
#include "cobmain.h"
#include "global.h"
#include "util/reswords.h"


#define BUFFERSIZE 1024
#define DBG_LINENO yylineno - 1

#undef YY_INPUT
#define YY_INPUT(b,r,ms) { r = myinput(b, ms); ++yylineno; }

/* temporary values */
//TODO: these should be moved to some other place. Check later

char tmpStr[BUFFERSIZE];

#define string_token() strncpy(tmpStr, yytext,sizeof(tmpStr))

char *removeQuote(int left, int right);


#line 695 "lex.yy.c"

#define INITIAL 0
#define PIC_STATE 1
#define VALUE_STATE 2
#define TXT_STATE 3
#define ID_STATE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 72 "token.l"


#line 897 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 164 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 640 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 74 "token.l"
{
        BEGIN(PIC_STATE);
        dbg_print(DBG_TOK, "%d: Found PIC    : %s\n", DBG_LINENO, yytext);
        return PICTURE;
    }
	YY_BREAK
/***************** PIC_STATE **********************/

case 2:
YY_RULE_SETUP
#line 82 "token.l"
{ return IS; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "token.l"
{ return ARE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "token.l"
{
    BEGIN(INITIAL);
    dbg_print(DBG_TOK, "%d: picstr nines   : %s\n", DBG_LINENO, yytext);
    yylval.sval = yytext;    
    return PICTURE_STR;
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "token.l"
{
    BEGIN(INITIAL);
    dbg_print(DBG_TOK, "%d: picstr nine-length   : %s\n", DBG_LINENO, yytext);   
    yylval.sval = yytext;
    return PICTURE_STR;
    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 "token.l"
{
    BEGIN(INITIAL);
    dbg_print(DBG_TOK, "%d: picstr nineswithV   : %s\n", DBG_LINENO, yytext);   
    yylval.sval = yytext;
    return PICTURE_STR;
    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "token.l"
{
    BEGIN(INITIAL);
    dbg_print(DBG_TOK, "%d: picstr xes-length   : %s\n", DBG_LINENO, yytext);   
    yylval.sval = yytext;
    return PICTURE_STR;
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 109 "token.l"
{
    BEGIN(INITIAL);
    dbg_print(DBG_TOK, "%d: picstr xes   : %s\n", DBG_LINENO, yytext);   
    yylval.sval = yytext;
    return PICTURE_STR;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 115 "token.l"
{ 
    BEGIN(INITIAL);
    dbg_print(DBG_TOK, "%d: general pic  : %s\n", DBG_LINENO, yytext);   
    yylval.sval = yytext;
    return PICTURE_STR;
    }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 121 "token.l"
{ 
        dbg_print(0, "333%d: space    : %s\n", DBG_LINENO, yytext); 
    } 
	YY_BREAK
/* end PIC_STATE */

case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 127 "token.l"
{ 
        BEGIN(INITIAL);
        dbg_print(DBG_TOK, "%d: period inside PIC-INITIAL   : %s\n", DBG_LINENO, yytext);
        return PERIOD;
    }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 132 "token.l"
{ 
        dbg_print(0, "555 %d: space    : %s\n", DBG_LINENO, yytext);
        BEGIN(INITIAL);
    }
	YY_BREAK

/*************** Outside any state ******************/
case 13:
YY_RULE_SETUP
#line 138 "token.l"
{
	/* string literal */
	return read_literal_str(yytext[0]);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 143 "token.l"
{
        dbg_print(0, "%d: POW_OP   : %s\n", DBG_LINENO, yytext); 
        return _POW_OP;    
    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 147 "token.l"
{ 
        dbg_print(DBG_TOK, "%d: dquote -outside  : %s\n", DBG_LINENO, yytext); 
        string_token(); 
        yylval.sval = removeQuote(1, 1);
        return DQUOTE_LITERAL;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 153 "token.l"
{ 
        dbg_print(DBG_TOK, "%d: squote   : %s\n", DBG_LINENO, yytext); 
        string_token(); 
        yylval.sval = removeQuote(1, 1);
        return SQUOTE_LITERAL;
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 159 "token.l"
{ 
        dbg_print(DBG_TOK, "%d: integer   : %s\n", DBG_LINENO, yytext);
        yylval.ival = atoi(yytext);
        return INTEGER_LITERAL;
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 164 "token.l"
{ 
        dbg_print(DBG_TOK, "%d: number   : %s\n", DBG_LINENO, yytext);
        yylval.fval = atof(yytext);
        return NUMBER_LITERAL;
    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 169 "token.l"
{
        dbg_print(DBG_TOK, "%d: hex_num  : %s\n", DBG_LINENO, yytext); 
        string_token();
        yylval.longVal = strtol( removeQuote(2, 1), NULL, 16);  
                /* remove H|h and DQuote  */
        return HEX_NUMBER_LITERAL;
    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 176 "token.l"
{
        dbg_print(DBG_TOK, "%d: hex_literal: %s\n", DBG_LINENO, yytext);        
        string_token();
        yylval.sval = removeQuote(2, 1); /* remove H|h and SQUOTE */
        return HEX_STRING;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 182 "token.l"
{ 
        int retcode = 0;
        if ((retcode = reserved(yytext)) != 0 ){

            struct reserved_sym *sym = lookup_reserved(yytext);
            dbg_print(DBG_TOK, "%d: Keyword    : %s\n", DBG_LINENO, sym->name); 
            yylval.sval = yytext;
            if( retcode == EQ ) { 
                dbg_print(DBG_TOK, "%d: Found equal sign ... should you find it\n", DBG_LINENO); 
            }
            if( retcode == LT ) {
                dbg_print(DBG_TOK, "%d: Found LT sign ... should you find it\n", DBG_LINENO); 
            }
            if( retcode == GT ) {
                dbg_print(DBG_TOK, "%d: Found GT sign ... should you find it\n", DBG_LINENO); 
            }

            return retcode;
        } 
        else {
            /* this is not a keyword */
            dbg_print(DBG_TOK, "%d: Outside ID state identifier : %s\n", DBG_LINENO, yytext);
            yylval.sval = strdup(yytext);
            BEGIN(ID_STATE);
            return IDENTIFIER;
        }
    }
	YY_BREAK
case 22:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 209 "token.l"
{
            /* this is the comment */
        dbg_print(DBG_TOK, "%d: **** identified comment **** \n", DBG_LINENO);
    }
	YY_BREAK
/*
 
^"D".* { 
             this is the comment. This could be used for debug mode as well 
    }
  */
case 23:
YY_RULE_SETUP
#line 219 "token.l"
{
        /* ignore for time being. */
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 223 "token.l"
{

}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 227 "token.l"
{
        int retcode = 0;
        if ((retcode = reserved(yytext)) != 0 ){
            struct reserved_sym *sym = lookup_reserved(yytext);
            dbg_print(DBG_TOK, "%d: Keyword    : %s\n", DBG_LINENO, sym->name); 
            yylval.sval = yytext;
            dbg_print(DBG_TOK, "%d: Found relational operator ... %d\n", DBG_LINENO, retcode);
            return retcode;
        }
        else {
            dbg_print(DBG_TOK, "Unknown relational operator at %d\n", yylineno);
        }
    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 241 "token.l"
{ dbg_print(DBG_TOK, "%d: The plus sign.\n", DBG_LINENO); return _PLUS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 242 "token.l"
{ dbg_print(DBG_TOK, "%d: The minus sign.\n", DBG_LINENO); return _MINUS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 243 "token.l"
{ dbg_print(DBG_TOK, "%d: The multiply sign.\n", DBG_LINENO); return _MULTIPLY; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 244 "token.l"
{ dbg_print(DBG_TOK, "%d: The divide sign.\n", DBG_LINENO); return _DIVIDE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 246 "token.l"
{ /* BEGIN(ID_STATE); */ dbg_print(DBG_TOK,"inside the lparan starting ID_STATE\n"); return LPARAN_SUB; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 247 "token.l"
{ dbg_print(DBG_TOK, "inside the RPARAN_SUB outside IDSTATE\n"); return RPARAN_SUB; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 248 "token.l"
{ 
        /* BEGIN(INITIAL); */
        return COMMA; 
    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 253 "token.l"
{     }
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 254 "token.l"
{     }
	YY_BREAK
/********************** ID_STATE **************************/

case 35:
YY_RULE_SETUP
#line 258 "token.l"
{
        BEGIN(PIC_STATE);
        dbg_print(DBG_TOK, "%d: Found PIC    : %s\n", DBG_LINENO, yytext);
        return PICTURE;
    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 263 "token.l"
{ 
        /* BEGIN(INITIAL); */
        return COMMA; 
    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 268 "token.l"
{   /* BEGIN(INITIAL); */ }
	YY_BREAK
case 38:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 270 "token.l"
{
            /* this is the comment */
        dbg_print(DBG_TOK, "%d: **** identified comment **** \n", DBG_LINENO);
    }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 274 "token.l"
{ 
        BEGIN(INITIAL);
        dbg_print(DBG_TOK, "%d: Period    : %s\n", DBG_LINENO, yytext);
        return PERIOD;
    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 279 "token.l"
{ 
        dbg_print(DBG_TOK, "%d: integer   : %s\n", DBG_LINENO, yytext);
        yylval.ival = atoi(yytext);
        return INTEGER_LITERAL;
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 284 "token.l"
{ 
        int retcode = 0;
        if ((retcode = reserved(yytext)) != 0 ){
            struct reserved_sym *sym = lookup_reserved(yytext);
            dbg_print(DBG_TOK, "%d: Inside ID SCOPE Keyword    : %s\n", DBG_LINENO, sym->name); 
            yylval.sval = yytext;
            if( retcode == EQ ) { 
                dbg_print(DBG_TOK, "%d: Found equal sign ... should you find it\n", DBG_LINENO); 
            }
            if( retcode == LT ) {
                dbg_print(DBG_TOK, "%d: Found LT sign ... should you find it\n", DBG_LINENO); 
            }
            if( retcode == GT ) {
                dbg_print(DBG_TOK, "%d: Found GT sign ... should you find it\n", DBG_LINENO); 
            }

            BEGIN(INITIAL); 
            return retcode;
        } 
        else {
            /* this is not a keyword */
            dbg_print(DBG_TOK, "%d: Inside ID SCOPE Identifier : %s\n", DBG_LINENO, yytext);
            yylval.sval = yytext;
            /* BEGIN(INITIAL); */
            return IDENTIFIER;
        }
    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 311 "token.l"
{
        int retcode = 0;
        if ((retcode = reserved(yytext)) != 0 ){
            struct reserved_sym *sym = lookup_reserved(yytext);
            dbg_print(DBG_TOK, "%d: Keyword    : %s\n", DBG_LINENO, sym->name); 
            yylval.sval = yytext;
            dbg_print(DBG_TOK, "%d: Found relational operator ... %d\n", DBG_LINENO, retcode);
            return retcode;
        }
        else {
            dbg_print(DBG_TOK, "Unknown relational operator at %d\n", yylineno);
        }
    }
	YY_BREAK
/*
[=] { return EQ; }
[>] { return GT; }
[<] { return LT; }
"<=" { return LE; }
">=" { return GE; }
 */
case 43:
YY_RULE_SETUP
#line 332 "token.l"
{  dbg_print(DBG_TOK, "inside the lparan ID_state\n"); return LPARAN_SUB;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 333 "token.l"
{  dbg_print(DBG_TOK, "inside the RPARAN_SUB insiade IDSTATE\n"); /* BEGIN(INITIAL); */ return RPARAN_SUB; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 335 "token.l"
{
        dbg_print(DBG_TOK, "%d: POW_OP              : %s\n", DBG_LINENO, yytext); 
        return _POW_OP;    
    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 339 "token.l"
{ 
        dbg_print(DBG_TOK, "%d: Dquote String- id_state       : %s\n", DBG_LINENO, yytext); 
        string_token();   yylval.sval = removeQuote(1, 1);
        return DQUOTE_LITERAL;
    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 344 "token.l"
{ 
        dbg_print(DBG_TOK, "%d: Squote String       : %s\n", DBG_LINENO, yytext); 
        string_token();   yylval.sval = removeQuote(1, 1);
        return SQUOTE_LITERAL;
    } 
	YY_BREAK
/*
{integer}  { 
        dbg_print(DBG_TOK, "%d: Integer             : %s\n", DBG_LINENO, yytext);
        yylval.ival = atoi(yytext);
        return INTEGER_LITERAL;
    } 
    */
case 48:
YY_RULE_SETUP
#line 356 "token.l"
{ 
        dbg_print(DBG_TOK, "%d: number   : %s\n", DBG_LINENO, yytext);
        yylval.fval = atof(yytext);
        return NUMBER_LITERAL;
    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 361 "token.l"
{
        dbg_print(DBG_TOK, "%d: hex_num  : %s\n", DBG_LINENO, yytext); 
        string_token();  yylval.longVal = strtol( removeQuote(2, 1), NULL, 16);  
                /* remove H|h and DQuote  */
        return HEX_NUMBER_LITERAL;
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 367 "token.l"
{
        dbg_print(DBG_TOK, "%d: hex_literal: %s\n", DBG_LINENO, yytext);        
        string_token();  yylval.sval = removeQuote(2, 1); 
            /* remove H|h and SQUOTE */
        return HEX_STRING;
    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 373 "token.l"
{ dbg_print(DBG_TOK, "%d: The plus sign.\n", DBG_LINENO); return _PLUS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 374 "token.l"
{ dbg_print(DBG_TOK, "%d: The minus sign.\n", DBG_LINENO); return _MINUS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 375 "token.l"
{ dbg_print(DBG_TOK, "%d: The multiply sign.\n", DBG_LINENO); return _MULTIPLY; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 376 "token.l"
{ dbg_print(DBG_TOK, "%d: The divide sign.\n", DBG_LINENO); return _DIVIDE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 377 "token.l"
{ dbg_print(DBG_TOK, "%d: The colon sign.\n", DBG_LINENO); return _COLON; }
	YY_BREAK
/* check for added new lines... */
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 379 "token.l"
{ 
        dbg_print(0, "333%d: space    : %s\n", DBG_LINENO, yytext); 
    } 
	YY_BREAK

case 57:
YY_RULE_SETUP
#line 386 "token.l"
ECHO;
	YY_BREAK
#line 1517 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PIC_STATE):
case YY_STATE_EOF(VALUE_STATE):
case YY_STATE_EOF(TXT_STATE):
case YY_STATE_EOF(ID_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 164 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 164 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 163);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 386 "token.l"



int myinput( char *buff, int max_size) {

    int	ipchar;
    size_t	gotcr;
    int	i;
    int	n;
    int forward;
    int	coln;

    /* initialize the buffer to all 0 */
    memset (buff, 0, 256);


    /* read a line assumed that no line longer than 256 */
    ipchar = 0;
    forward = 0;
    for (n = 0; n < 256 && ipchar != '\n';) {
        ipchar = getc (yyin);
        forward++;
        if (ipchar == EOF) {
            if (n == 0) {
                return 0;
            }
            memset (buff, '\n', n);
            buff[n] = 0;
            // newline_count = 0; 
            return strlen (buff);
        }

        // Try removing the numbers in case of FIXED format.
        if ( file_format == FIXED ){
            if( forward == 1){ 
                /* seen somewhere that the six digits are not necessarily numeric */
                for(; forward++ < 7 ; ) {
                    ipchar = getc(yyin);
                        if (ipchar == EOF ) break;
                }
            }
            // forward is going to be past n now after skipping the six leading chars. 
            if( forward == 74){
                ipchar = getc(yyin);
                while( (forward++ < 82) && (ipchar != '\n') && (ipchar != EOF)) 
                    ipchar = getc(yyin);
            }
        }
        // dbg_print(DBG_TOK, "%c", ipchar); 
        // comments to be handled in the lexer. 

        buff[n++] = ipchar;
    }
    dbg_print(DBG_TOK, "New input line: %s\n", buff);
    /* yylineno++; */
    currentline = buff;
    return strlen (buff);
}

static int
read_literal_str (int quote)
{
	size_t	i = 0;
	int		c;

        dbg_print(DBG_TOK,"**** Inside read_literal_str function ****\n");
	if (!plexbuff) {
		plexbuff = calloc (1, COB_MINI_BUFF);
		plexsize = COB_MINI_BUFF;
	}

	while ((c = input ()) != EOF) {
		plexbuff[i++] = c;
		if (c == quote && (c = input()) != quote) {
			i--;
			unput (c);
			break;
		}
		if (i >= plexsize) {
			plexsize *= 2;
			plexbuff = realloc (plexbuff, plexsize);
		}
	}
	if (!i) {
		dbg_print(DBG_TOK, "Alphanumeric literal has zero length, A SPACE will be assumed.\n");
		i = 1;
		plexbuff[0] = ' ';
	}
	plexbuff[i] = 0;
	yylval.sval = plexbuff;

    dbg_print(DBG_TOK, "**** str value : %s\n", plexbuff);
    
    if (quote == '\"') return DQUOTE_LITERAL;
	return SQUOTE_LITERAL;
}

char *removeQuote(int left, int right) {
  char *s2, *s1;
  int strLength;
  
  s1 = tmpStr;
  strLength = strlen(s1);
  if ( (strLength - left - right) > 0 ) {
    s2 = s1 + strLength - right;
    *s2 = '\0';
    s2 = s1 + left;
    while (*s1 != '\0') {
      *s1 = *s2;
      s1++;
      s2++;
    }
  }
  return (char *)tmpStr;
}

